### ISSUE TITLE
Multiple Heartbeat Subscribe Bug

### ISSUE THREAD

**Issue by adamseth2** [TrickfireRobotics/mission-control#32]
# Context
If the page reloads, especially during hot load, the interval for the heartbeat has multiple running at the same time rather than just one (Can look in the console as the number goes in factors of 2+ at the same time)

# How To Fix
in Store/useRos, in the interval, somehow when the page refreshes, to only have one instance being run one

**Comment by uellenberg** [comment]
Fixed in 494780b22dd28fd4520f8f6987164b4540bad4b8
