### ISSUE TITLE
Deploying Project for Non-Software Members

### ISSUE THREAD

**Issue by adamseth2** [TrickfireRobotics/mission-control#34]
# Context
Non-software members have requested an easy way to access mission control UI without having to set up npm, npm install etc. Due to browser security having CORS, `npm run build` simply doesn't work. 
Error I get: 
``` Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/Coding%20Projects/mission-control/dist/assets/index-4e95f69b.js. (Reason: CORS request not http).``` [Can read why here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)

# How to implement
Figure out what the easiest way (aka not installing a lot of dependencies) to have a way to access the mission control without installing anything. What seems the easiest is hosting it on GitHub Pages so we can have a HTTP/ HTTPS connection, fixing the CORS issue. Another could be having release versions in GitHub.

**Comment by uellenberg** [comment]
GitHub Pages has been implemented, although doesn't quite work yet due to build errors (fixed by #35).
